### PR TITLE
Solves problem with building for os x with xcode 4

### PR DESCRIPTION
**Pull request by piranha**
I'm not sure this is the right way to go, but it solves problem for me - I'm not a Ruby programmer, so I'm not completely sure how would you check in this place if you're on OS X or not and if you should do that. That's basically a request to fix it properly, if I may ask for that.

### CODE REVIEW

**Comment by rvnd** [comment]
Worked for me too.

**Comment by wmorgan** [comment]
The "-arch i386" flag is included by your Ruby installation, so I'm reluctant to just comment it out.,
1. What is the compilation error message you see?
2. What version of Ruby are you running?
3. Are you running on a PowerPC-based Macintosh, by any chance?
4. Are you able to install other gems that have a C component? E.g. can you successfully `gem install whistlepig`?

**Comment by piranha** [comment]
1. see below
2. ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]
3. no
4. yes, no problems

```
piranha@gto ~> gem install leveldb-ruby  
Building native extensions.  This could take a while...
ERROR:  Error installing leveldb-ruby:
    ERROR: Failed to build gem native extension.

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby extconf.rb
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/builder.cc -o db/builder.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/db_impl.cc -o db/db_impl.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/db_iter.cc -o db/db_iter.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/filename.cc -o db/filename.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/dbformat.cc -o db/dbformat.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/log_reader.cc -o db/log_reader.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/log_writer.cc -o db/log_writer.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/memtable.cc -o db/memtable.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/repair.cc -o db/repair.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/table_cache.cc -o db/table_cache.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/version_edit.cc -o db/version_edit.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/version_set.cc -o db/version_set.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 db/write_batch.cc -o db/write_batch.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 port/port_osx.cc -o port/port_osx.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/block.cc -o table/block.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/block_builder.cc -o table/block_builder.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/format.cc -o table/format.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/iterator.cc -o table/iterator.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/merger.cc -o table/merger.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/table.cc -o table/table.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/table_builder.cc -o table/table_builder.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 table/two_level_iterator.cc -o table/two_level_iterator.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/arena.cc -o util/arena.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/cache.cc -o util/cache.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/coding.cc -o util/coding.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/comparator.cc -o util/comparator.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/crc32c.cc -o util/crc32c.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/env.cc -o util/env.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/env_posix.cc -o util/env_posix.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/hash.cc -o util/hash.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/histogram.cc -o util/histogram.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/logging.cc -o util/logging.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/options.cc -o util/options.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG -fPIC  -DUSE_SNAPPY=1 util/status.cc -o util/status.o
rm -f libleveldb.a
ar -rs libleveldb.a ./db/builder.o ./db/db_impl.o ./db/db_iter.o ./db/filename.o ./db/dbformat.o ./db/log_reader.o ./db/log_writer.o ./db/memtable.o ./db/repair.o ./db/table_cache.o ./db/version_edit.o ./db/version_set.o ./db/write_batch.o ./port/port_osx.o ./table/block.o ./table/block_builder.o ./table/format.o ./table/iterator.o ./table/merger.o ./table/table.o ./table/table_builder.o ./table/two_level_iterator.o ./util/arena.o ./util/cache.o ./util/coding.o ./util/comparator.o ./util/crc32c.o ./util/env.o ./util/env_posix.o ./util/hash.o ./util/histogram.o ./util/logging.o ./util/options.o ./util/status.o
ar: creating archive libleveldb.a
creating Makefile

make
g++ -I. -I/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin11.0 -I/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin11.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -arch i386 -arch x86_64 -g -Os -pipe -fno-common -DENABLE_DTRACE  -fno-common  -pipe -fno-common  -I../../leveldb/include   -c leveldb.cc
g++ -shared -o leveldb.bundle leveldb.o -L. -L/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib -L. -arch i386 -arch x86_64     -lruby  -lpthread -ldl   -L../../leveldb -lleveldb
ld: warning: ignoring file ../../leveldb/libleveldb.a, file was built for archive which is not the architecture being linked (i386)
Undefined symbols for architecture i386:
  "leveldb::Options::Options()", referenced from:
      db_make(unsigned long, unsigned long, unsigned long, unsigned long)in leveldb.o
  "leveldb::DB::Open(leveldb::Options const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)", referenced from:
      db_make(unsigned long, unsigned long, unsigned long, unsigned long)in leveldb.o
  "leveldb::Status::ToString() const", referenced from:
      db_make(unsigned long, unsigned long, unsigned long, unsigned long)in leveldb.o
      db_get(unsigned long, unsigned long)in leveldb.o
      db_delete(unsigned long, unsigned long)in leveldb.o
      db_put(unsigned long, unsigned long, unsigned long)in leveldb.o
      db_size(unsigned long)in leveldb.o
      db_each(unsigned long)in leveldb.o
  "leveldb::Status::CopyState(char const*)", referenced from:
      db_delete(unsigned long, unsigned long)in leveldb.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status
lipo: can't open input file: /var/folders/3d/1j2kw66x3g3g5syddr8w8c840000gn/T//ccRfyJYt.out (No such file or directory)
make: *** [leveldb.bundle] Error 1


Gem files will remain installed in /usr/local/Cellar/Gems/1.8/gems/leveldb-ruby-0.7 for inspection.
Results logged to /usr/local/Cellar/Gems/1.8/gems/leveldb-ruby-0.7/ext/leveldb/gem_make.out
```

**Comment by wmorgan** [comment]
I've just released 0.8 which includes the latest leveldb code. I don't think this will fix your issue, but please give it a try for good measure.

**Comment by piranha** [comment]
Just tried it - same problem. :(

**Comment by wmorgan** [comment]
Ok, I've fixed this in 0.10. Please reopen if that doesn't work for you.

**Comment by piranha** [comment]
It works, thank you.

**Pull request closed without merging**
