### PR TITLE
Update

### PR DESCRIPTION
**Pull request by schmurfy**
I updated the gem to use the latest leveldb version directly from the google git repository.

This fix the "Symbol not found: __ZN6snappy19MaxCompressedLengthEm" problem for me on mac os x lion.

### CODE REVIEW

**Comment by wmorgan** [comment]
Awesome. I will merge this in once I have a chance to do a little testing. Thank you.

**Comment by wmorgan** [comment]
After playing around with it some, I'm not sure this is a good idea.

For one, currently I have to tweak the leveldb Makefile every time I update the code. See e.g. commits efd37b47b358278f47fe1e550ae31b012fbbff4a and b93c383eab98ba7175a1a8ba354c142444f9cb1a. We'd have to find an equivalent thing when that code is checked out in a submodule. Every solution I can think of is very complex, but maybe you have a simple option.

And the the 'rake gem' task is going to have to do some work to ensure that the code is in the submodule dir, otherwise we risk shipping gems with missing pieces if you don't remember to do the magic submodule incantation.

**Comment by schmurfy** [comment]
Latest leveldb allow to redefine $OPT which allows this:

```
OPT="-O2 -DNDEBUG -fPIC" make all
```

I am not sure how to integrate this into the build process but it would allow compiling untouched sources which is always better (and make upgrades so much easier too).

For the submodule a simple approach could be to add a "git submodule update --init" before building the gem, "git submodule" also show you if the submodules are up to date or not so a check should be possible.

For the first point I have no idea how to do in your build process but for the later I can have a look if you want.

**Comment by wmorgan** [comment]
Closing this out.

I've updated master to use the OPT trick. Thanks! I think I'm going to stick with manual updates for the time being, though.

I've updated the code to leveldb 1.5. Please reopen if you are still having this issue.

**Pull request closed without merging**
